service: emprende-candelaria-api

provider:
  name: aws
  runtime: python3.11
  stage: dev
  region: us-east-1
  profile: personal 
  environment:
    DJANGO_SETTINGS_MODULE: haztever.settings
    DEBUG: "false"
    HOST: ${aws:ssm:/emprende-candelaria/dev/HOST}
    # Para aurora
    # DB_NAME: ${aws:ssm:/emprende-candelaria/dev/DB_NAME}
    # DB_USER: ${aws:ssm:/emprende-candelaria/dev/DB_USER}
    # DB_PASSWORD: ${aws:ssm:/emprende-candelaria/dev/DB_PASSWORD}   
    # DB_HOST: ${aws:ssm:/emprende-candelaria/dev/DB_HOST}
    # DB_PORT: "5432"

    #Neon database
    DATABASE_URL: ${aws:ssm:/emprende-candelaria/dev/DATABASE_URL}
    SECRET_KEY: ${aws:ssm:/emprende-candelaria/dev/SECRET_KEY}
    AWS_STORAGE_BUCKET_NAME: ${aws:ssm:/emprende-candelaria/dev/AWS_STORAGE_BUCKET_NAME}
  
    #Email configuration
    EMAIL_HOST: ${aws:ssm:/haztever/dev/EMAIL_HOST}
    EMAIL_PORT: ${aws:ssm:/haztever/dev/EMAIL_PORT}
    EMAIL_HOST_USER: ${aws:ssm:/haztever/dev/EMAIL_HOST_USER}
    EMAIL_HOST_PASSWORD: ${aws:ssm:/haztever/dev/EMAIL_HOST_PASSWORD}  
    DEFAULT_FROM_EMAIL: ${aws:ssm:/haztever/dev/DEFAULT_FROM_EMAIL}

  # Para aurora
  # vpc:
    # securityGroupIds:
    #   - sg-0acb15dc77c8a0f14
    # subnetIds:
    #   - subnet-0b1289f34e539fb81
    #   - subnet-023669c5a7f4a420d

  iamRoleStatements:
    - Effect: Allow
      Action:
        - ssm:GetParameter
        - ssm:GetParameters
      Resource:
        - arn:aws:ssm:us-east-1:*:parameter/emprende-candelaria/dev/*

plugins:
  - serverless-python-requirements
  - serverless-wsgi

package:
  patterns:
    - '!node_modules/**'
    - '!.env/**'
    - '!.gitignore'
    - '!.git/**'
    - '!venv/**'
    - '!.venv/**'
    - '!*.pyc'
    - '!__pycache__/**'
    - '!.serverless/**'
    - '!docs/**'
    - '!README.md'
    - '!.DS_Store'

custom:
  wsgi:
    app: haztever.wsgi.application
  pythonRequirements:
    dockerizePip: true
    slim: true
    strip: false
    noDeploy:
      - boto3          
      - botocore       
      - urllib3

functions:
  api:
    handler: wsgi_handler.handler
    timeout: 30
    memorySize: 512
    events:
      - http: 
          path: /{proxy+}
          method: ANY
          cors: true
      - http: 
          path: /
          method: ANY
          cors: true