# Generated by Django 5.2.4 on 2025-07-20 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('business_name', models.CharField(max_length=200, unique=True)),
                ('logo', models.ImageField(upload_to='business_logos/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='business_banners/')),
                ('whatsapp', models.CharField(max_length=20)),
                ('social_networks', models.JSONField(blank=True, null=True, verbose_name='Secondary social networks')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
