# Generated by Django 5.2.4 on 2025-07-14 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('business_name', models.CharField(max_length=200, unique=True)),
                ('logo', models.ImageField(upload_to='business_logos/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='business_banners/')),
                ('whatsapp', models.CharField(max_length=20)),
                ('social_networks', models.JSONField(blank=True, null=True, verbose_name='Secondary social networks')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(related_name='business_profiles', to='business.category')),
            ],
        ),
    ]
